# Stage 1: Build aplikasinya
FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Build apliikasi go
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Stage 2: Bikin image 
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]